import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/auth";
import Head from "@/components/Head";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inventory App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Head></Head>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
